[project]
requires-python = ">=3.10"

[tool.ruff]
exclude = [
    "__init__.py",
    "tests/",
]
line-length = 120

[tool.ruff.lint]
ignore-init-module-imports = true
select = [
    "F", # pyflakes rules
    "I001", # unsorted-imports
    "I002", # missing-required-import
]
ignore = [
    "F403", # undefined-local-with-import-star
    "F405", # undefined-local-with-import-star-usage
    "F821", # undefined-name
    "F841", # unused-variable
]
